# Generated by Django 5.0.1 on 2024-01-16 07:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=250, unique=True)),
                ('category_slug', models.CharField(max_length=500, unique=True)),
                ('category_image', models.ImageField(upload_to='category_images/')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('sub_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.category')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=500, unique=True)),
                ('product_slug', models.CharField(max_length=500, unique=True)),
                ('product_card_image', models.ImageField(unique='product_card_image/', upload_to='')),
                ('recently_add', models.BooleanField(default=False)),
                ('trending', models.BooleanField(default=False)),
                ('popular_in_category', models.BooleanField(default=False)),
                ('is_available', models.BooleanField(default=False)),
                ('price', models.DecimalField(decimal_places=3, max_digits=25, max_length=25)),
                ('stock', models.IntegerField()),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('category_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.category')),
            ],
        ),
    ]
