# Generated by Django 5.0.1 on 2024-01-16 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_alter_category_sub_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='recently_add',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='category',
            name='trending',
            field=models.BooleanField(default=False),
        ),
    ]
