# Generated by Django 5.0.1 on 2024-01-16 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_brands_rename_price_product_selling_price_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='brands',
            options={'verbose_name': 'Brands', 'verbose_name_plural': 'Brands'},
        ),
        migrations.AddField(
            model_name='product',
            name='product_description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
