# Generated by Django 5.0.1 on 2024-01-21 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0013_alter_galleryimage_gallery_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='max_quantity',
            field=models.IntegerField(default=10),
        ),
        migrations.AddField(
            model_name='product',
            name='min_quantity',
            field=models.IntegerField(default=1),
        ),
    ]
