# Generated by Django 5.0.1 on 2024-02-16 05:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0014_product_max_quantity_product_min_quantity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='product_description',
        ),
    ]
